version: "3.7"

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test-admin-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - db_volume:/db_volume
      - backup_volume:/backup_volume
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_volume:
  backup_volume:
