version: "3.7"

services:

  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test-admin-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      #- ./data:/var/lib/postgresql/data
      - ./backup:/backup_volume

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
